/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hr.algebra;

import hr.algebra.model.Actor;
import hr.algebra.model.ActorAddable;
import hr.algebra.model.Director;
import hr.algebra.model.DirectorAddable;
import hr.algebra.model.Genre;
import hr.algebra.model.GenreAddable;
import hr.algebra.model.Role;
import hr.algebra.model.User;
import hr.algebra.utilities.MessageUtils;
import hr.algebra.view.ActorPanel;
import hr.algebra.view.DirectorPanel;
import hr.algebra.view.EditMoviesPanel;
import hr.algebra.view.GenrePanel;
import hr.algebra.view.LoginPanel;
import hr.algebra.view.RegisterPanel;
import hr.algebra.view.UploadMoviesPanel;
import hr.algebra.view.UserPanel;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Action;
import javax.swing.ActionMap;
import javax.swing.ButtonGroup;
import javax.swing.JMenuItem;
import javax.swing.JRadioButtonMenuItem;
import javax.swing.KeyStroke;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.text.DefaultEditorKit;

/**
 *
 * @author daniel.bele
 */
public class MovieManager extends javax.swing.JFrame implements ActorAddable, GenreAddable, DirectorAddable {

    private boolean edited;
    private ActorPanel actorPanel;
    private GenrePanel genrePanel;
    private DirectorPanel directorPanel;

    /**
     * Creates new form ArticleManager
     */
    public MovieManager() {
        initComponents();
        actorPanel = new ActorPanel();
        genrePanel = new GenrePanel();
        directorPanel = new DirectorPanel();
        handleEditMenu();
        handleLookAndFeelMenu();
        setupLoginRegisterPanels();
    }

    public void postLoginSetup() {
        int loginIndex = tpContent.indexOfTab("Login");
        if (loginIndex != -1) {
            tpContent.remove(loginIndex);
        }
        int registerIndex = tpContent.indexOfTab("Register");
        if (registerIndex != -1) {
            tpContent.remove(registerIndex);
        }
        configurePanels();
        showMainPanel();

    }

    private static User loggedInUser;

    public static void setLoggedInUser(User user) {
        loggedInUser = user;
    }

    public static User getLoggedInUser() {
        return loggedInUser;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpContent = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        miPageSetup = new javax.swing.JMenuItem();
        miPrint = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        miExit = new javax.swing.JMenuItem();
        menuEdit = new javax.swing.JMenu();
        menuView = new javax.swing.JMenu();
        menuLF = new javax.swing.JMenu();
        menuHelp = new javax.swing.JMenu();
        miAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Movie manager");

        tpContent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tpContentKeyReleased(evt);
            }
        });

        menuFile.setMnemonic('F');
        menuFile.setText("Application");

        miPageSetup.setText("Page Setup");
        miPageSetup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPageSetupActionPerformed(evt);
            }
        });
        menuFile.add(miPageSetup);

        miPrint.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miPrint.setText("Print");
        miPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPrintActionPerformed(evt);
            }
        });
        menuFile.add(miPrint);
        menuFile.add(jSeparator2);

        miExit.setText("Exit");
        miExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExitActionPerformed(evt);
            }
        });
        menuFile.add(miExit);

        jMenuBar1.add(menuFile);

        menuEdit.setMnemonic('E');
        menuEdit.setText("Edit");
        jMenuBar1.add(menuEdit);

        menuView.setMnemonic('V');
        menuView.setText("View");

        menuLF.setMnemonic('L');
        menuLF.setText("Look and feel");
        menuView.add(menuLF);

        jMenuBar1.add(menuView);

        menuHelp.setMnemonic('H');
        menuHelp.setText("Help");

        miAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miAbout.setText("About");
        miAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAboutActionPerformed(evt);
            }
        });
        menuHelp.add(miAbout);

        jMenuBar1.add(menuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpContent, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpContent, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void miAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAboutActionPerformed
        MessageUtils.showInformationMessage("MOVIE MANAGER", "Version 1.0");
    }//GEN-LAST:event_miAboutActionPerformed

    private void miPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPrintActionPerformed
        PrinterJob job = PrinterJob.getPrinterJob();

        if (job.printDialog()) {
            try {
                job.print();
            } catch (PrinterException ex) {
                Logger.getLogger(MovieManager.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_miPrintActionPerformed


    private void miExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExitActionPerformed
        dispose();
    }//GEN-LAST:event_miExitActionPerformed

    private void miPageSetupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPageSetupActionPerformed
        PrinterJob job = PrinterJob.getPrinterJob();
        job.pageDialog(job.defaultPage());
        try {
            job.print();
        } catch (PrinterException ex) {
            Logger.getLogger(MovieManager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_miPageSetupActionPerformed

    private void tpContentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tpContentKeyReleased
        edited = true;
    }//GEN-LAST:event_tpContentKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovieManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenu menuEdit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenu menuLF;
    private javax.swing.JMenu menuView;
    private javax.swing.JMenuItem miAbout;
    private javax.swing.JMenuItem miExit;
    private javax.swing.JMenuItem miPageSetup;
    private javax.swing.JMenuItem miPrint;
    private javax.swing.JTabbedPane tpContent;
    // End of variables declaration//GEN-END:variables

    private void configurePanels() {

        tpContent.removeAll();

        UserPanel userPanel;
        userPanel = new UserPanel();
       
       
        if(loggedInUser != null && loggedInUser.getRole()==Role.ADMIN)
        {
        tpContent.add(UPLOAD_MOVIES, new UploadMoviesPanel());
        tpContent.add(EDIT_MOVIES, new EditMoviesPanel());
        tpContent.add(ACTOR_PANEL, actorPanel);
        tpContent.add(DIRECTOR_PANEL, directorPanel);
        tpContent.add(GENRE_PANEL, genrePanel);
        tpContent.add(USER_PANEL,userPanel);
        } 
        else{
        tpContent.add(UPLOAD_MOVIES, new UploadMoviesPanel());
        tpContent.add(EDIT_MOVIES, new EditMoviesPanel());
         tpContent.add(USER_PANEL,userPanel);
        }

    }
    private static final String ACTOR_PANEL = "ACTOR ";
    private static final String DIRECTOR_PANEL = "DIRECTOR";
    private static final String GENRE_PANEL = "GENRE";
    private static final String USER_PANEL = "USER";
    private static final String EDIT_MOVIES = "MOVIES";
    private static final String UPLOAD_MOVIES = "UPLOAD MOVIES";
    private static final String REGISTER_PANEL = "REGISTER";
    private static final String LOGIN_PANEL = "LOGIN";

    private static final String DATE_FORMAT = "hh:mm dd.MM.yyyy";

    private void handleEditMenu() {
        ActionMap actionMap = tpContent.getActionMap();

        menuEdit.add(createItem(
                actionMap.get(DefaultEditorKit.cutAction),
                "Cut",
                KeyStroke.getKeyStroke(KeyEvent.VK_X,
                        InputEvent.CTRL_DOWN_MASK))
        );
        menuEdit.add(createItem(
                actionMap.get(DefaultEditorKit.copyAction),
                "Copy",
                KeyStroke.getKeyStroke(KeyEvent.VK_C,
                        InputEvent.CTRL_DOWN_MASK))
        );
        menuEdit.add(createItem(
                actionMap.get(DefaultEditorKit.pasteAction),
                "Paste",
                KeyStroke.getKeyStroke(KeyEvent.VK_V,
                        InputEvent.CTRL_DOWN_MASK))
        );
        menuEdit.addSeparator();
        menuEdit.add(createItem(
                actionMap.get(DefaultEditorKit.selectAllAction),
                "Select all",
                KeyStroke.getKeyStroke(KeyEvent.VK_A,
                        InputEvent.CTRL_DOWN_MASK))
        );

    }

    private JMenuItem createItem(Action action, String text, KeyStroke acc) {

        JMenuItem mi = new JMenuItem();
        mi.setAction(action);
        mi.setText(text);
        mi.setAccelerator(acc);
        return mi;
    }

    private void handleLookAndFeelMenu() {

        ButtonGroup bg = new ButtonGroup();
        Arrays.asList(UIManager.getInstalledLookAndFeels()).forEach(info -> {
            JRadioButtonMenuItem mi = new JRadioButtonMenuItem(info.getName());
            bg.add(mi);
            menuLF.add(mi);
            mi.setSelected("Nimbus".equals(info.getName()));
            mi.addActionListener(e -> {
                try {
                    UIManager.setLookAndFeel(info.getClassName());
                    SwingUtilities.updateComponentTreeUI(MovieManager.this);
                } catch (Exception ex) {
                    Logger.getLogger(MovieManager.class.getName()).log(Level.SEVERE, null, ex);
                }
            });

        });
    }

    @Override
    public boolean addActor(Actor actor) {
        return actorPanel.addActor(actor);
    }

    @Override
    public boolean addGenre(Genre genre) {
        return genrePanel.addGenre(genre);
    }

    @Override
    public boolean addDirector(Director director) {
        return directorPanel.addDirector(director);
    }

    private void showMainPanel() {
        tpContent.setSelectedIndex(tpContent.indexOfTab("Upload Movies"));
    }

    private void setupLoginRegisterPanels() {
        tpContent.removeAll();
        tpContent.add(REGISTER_PANEL, new RegisterPanel());
        tpContent.add(LOGIN_PANEL, new LoginPanel());
    }

    public void handleLogout() {
        tpContent.removeAll();
        setupLoginRegisterPanels();
        tpContent.setSelectedIndex(tpContent.indexOfTab("Login"));
    }

}
