movieRepo=hr.algebra.dal.sql.MovieRepositoryImpl
actorRepo=hr.algebra.dal.sql.ActorRepositoryImpl
directorRepo=hr.algebra.dal.sql.DirectorRepositoryImpl
genreRepo=hr.algebra.dal.sql.GenreRepositoryImpl
userRepo=hr.algebra.dal.sql.UserRepositoryImpl
