/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hr.algebra.view;

import hr.algebra.dal.GenreRepository;
import hr.algebra.dal.MovieRepository;
import hr.algebra.dal.RepositoryFactory;
import hr.algebra.dal.sql.GenreRepositoryImpl;
import hr.algebra.model.Director;
import hr.algebra.model.Genre;
import hr.algebra.model.GenreAddable;
import hr.algebra.model.GenreTransferable;
import hr.algebra.model.Movie;
import hr.algebra.model.MovieArchive;
import hr.algebra.parsers.rss.MovieParser;
import hr.algebra.utilities.JAXBUtils;
import java.awt.Frame;
import java.awt.Window;
import java.awt.datatransfer.Transferable;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.DropMode;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;
import javax.swing.TransferHandler;
import javax.xml.bind.JAXBException;

/**
 *
 * @author musam
 */
public class GenrePanel extends javax.swing.JPanel implements GenreAddable{

     private static final String FILENAME = "src/main/resources/moviearchive.xml";

private final GenreRepository genreRepository = new GenreRepositoryImpl();
private MovieRepository movieRepository;


private final List<Movie> movies = new ArrayList<>();
private final Set<Genre> genres = new TreeSet<>();
private final Set<Director> directors = new TreeSet<>();
private final Set<Genre> allGenres = new TreeSet<>();

private final DefaultListModel<Movie> moviesModel = new DefaultListModel<>();
private final DefaultListModel<Genre> genresModel = new DefaultListModel<>();
private final DefaultListModel<Genre> allGenresModel = new DefaultListModel<>();

private List<JLabel> errorLabels;


private void init() {
	initValidation();
	hideErrors();
	initDragNDrop();
        loadGenresFromDatabase();
       loadOrParseMovies();
}

private void initValidation() {
	
	errorLabels = Arrays.asList(lbGenresError);
}

private void hideErrors() {
	errorLabels.forEach(e -> e.setVisible(false));
}



private void loadGenresModel() {
	genresModel.clear();
	genres.forEach(genresModel::addElement);
	lsGenres.setModel(genresModel);
}	
	
private void loadAllGenresModel() {
	allGenresModel.clear();
	allGenres.forEach(allGenresModel::addElement);
	lsAllGenres.setModel(allGenresModel);
}

private void loadMoviesModel() {
	moviesModel.clear();
	movies.forEach(moviesModel::addElement);
	lsMovies.setModel(moviesModel);
}

    /**
     * Creates new form GenrePanel
     */
    public GenrePanel() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lsGenres = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lsMovies = new javax.swing.JList<>();
        btnAddGenre = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lsAllGenres = new javax.swing.JList<>();
        lbGenresError = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("All genres");

        jScrollPane3.setViewportView(lsGenres);

        jLabel3.setText("Genre");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lsMovies);

        btnAddGenre.setText("Add genre");
        btnAddGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddGenreActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(lsAllGenres);

        lbGenresError.setForeground(new java.awt.Color(204, 0, 0));
        lbGenresError.setText("X");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel1.setText("Movies");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRefresh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbGenresError, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btnAddGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbGenresError, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAddGenre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddGenreActionPerformed
        Window parent=SwingUtilities.getWindowAncestor(this);
        new AddGenreDialog( (Frame) parent,true).setVisible(true);
    }//GEN-LAST:event_btnAddGenreActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
         Movie selectedMovie = lsMovies.getSelectedValue();
         Genre selectedGenre = lsGenres.getSelectedValue();
         
         if (selectedMovie == null || selectedGenre == null) {
        JOptionPane.showMessageDialog(this, "Please select both a movie and a genre.");
        return;
         }
         try {
        movieRepository.updateMovieGenre(selectedMovie.getId(), selectedGenre.getId());

        
        JOptionPane.showMessageDialog(this, "Genre successfully assigned to movie!");

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Failed to assign genre to movie.");
    }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
         try {
             JAXBUtils.save(new MovieArchive(movies), FILENAME);
             JOptionPane.showMessageDialog(this,"Genres saved to XML successfully!","Success",
                     JOptionPane.INFORMATION_MESSAGE);
         } catch (JAXBException ex) {
             Logger.getLogger(GenrePanel.class.getName()).log(Level.SEVERE, null, ex);
              JOptionPane.showMessageDialog(this, "Failed to save movies to XML.", "Error", JOptionPane.ERROR_MESSAGE);
         }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed

    allGenres.addAll(genres);
    genres.clear();
    loadGenresModel();     
    loadAllGenresModel();  
      
    }//GEN-LAST:event_btnRefreshActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddGenre;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbGenresError;
    private javax.swing.JList<Genre> lsAllGenres;
    private javax.swing.JList<Genre> lsGenres;
    private javax.swing.JList<Movie> lsMovies;
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean addGenre(Genre genre) {
        if (allGenres.add(genre)) {
            loadAllGenresModel();

            return true;
        }
        return false;
    }

    private void initDragNDrop() {
        lsAllGenres.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        lsAllGenres.setDragEnabled(true);
        lsAllGenres.setTransferHandler(new ExportHandler());
        
        
        lsGenres.setDropMode(DropMode.ON);
        lsGenres.setTransferHandler(new GenrePanel.ImportHandler());
        
    }

    private void loadGenresFromDatabase()  {
        try {
            List<Genre> dbGenres = genreRepository.selectGenres();            
            allGenres.clear();
            allGenres.addAll(dbGenres);
            loadAllGenresModel();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Failed to load genres from database.");
        }
    }

    private void loadOrParseMovies()  {
        try {
            movieRepository = RepositoryFactory.getMovieRepository();
            
            List<Movie> dbMovies = movieRepository.selectMovies();
            if (dbMovies.isEmpty()) {
                List<Movie> parsedMovies = MovieParser.parse();
                movieRepository.createMovies(parsedMovies);
                dbMovies = parsedMovies;
            }
            
            movies.clear();
            movies.addAll(dbMovies);
            loadMoviesModel();
        } catch (Exception ex) {
                    Logger.getLogger(GenrePanel.class.getName()).log(Level.SEVERE, null, ex);
                     JOptionPane.showMessageDialog(this, "Failed to load or parse movies.");
        }
    }

    private  class ExportHandler extends TransferHandler {

        @Override
        public int getSourceActions(JComponent c) {
            return COPY;// Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
        }

        @Override
        protected Transferable createTransferable(JComponent c) {
            return new GenreTransferable(lsAllGenres.getSelectedValue()); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
        }

        
      
    }

    private class ImportHandler extends TransferHandler {

        @Override
        public boolean canImport(TransferSupport support) {
            return  support.isDataFlavorSupported(GenreTransferable.GENRE_FLAVOR);
        }

        @Override
        public boolean importData(TransferSupport support) {
            try {
                Transferable transferable=support.getTransferable();
                
                Genre data=(Genre)transferable.getTransferData(GenreTransferable.GENRE_FLAVOR);
                
                if (genres.add(data)) {
                    loadGenresModel();
                    return true;
                    
                }
                
            } catch (UnsupportedFlavorException | IOException ex) {
                Logger.getLogger(GenrePanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            return false;
        }
        

        
    }
}
