/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hr.algebra.view;

import hr.algebra.MovieManager;
import hr.algebra.dal.UserRepository;
import hr.algebra.dal.sql.UserRepositoryImpl;
import hr.algebra.model.Role;
import hr.algebra.model.User;
import hr.algebra.utilities.MessageUtils;
import java.awt.Window;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author musam
 */
public class UserPanel extends javax.swing.JPanel {

    private final UserRepository userRepository = new UserRepositoryImpl();
    /**
     * Creates new form UserPanel
     */
    public UserPanel() {
        initComponents();
        User user=MovieManager.getLoggedInUser();
        if (user!=null) {
        if (MovieManager.getLoggedInUser().getRole() == Role.ADMIN) {
        lblUsername.setText("Logged in as: " + MovieManager.getLoggedInUser().getUsername()+ "("+ MovieManager.getLoggedInUser().getRole()+")");     
           List<User> users = null;
            try {
                users = userRepository.selectUsers();
            } catch (Exception ex) {
                ex.printStackTrace();
                MessageUtils.showInformationMessage("Error", "Failed to load Users");
            }
            if (users != null && !users.isEmpty()) {
            String[] columnNames = { "ID", "Username", "Role" };
            Object[][] data = new Object[users.size()][3];
            for (int i = 0; i < users.size(); i++) {
                User u = users.get(i);
                data[i][0] = u.getId();
                data[i][1] = u.getUsername();
                data[i][2] = u.getRole().name();
            }
            DefaultTableModel model = new DefaultTableModel(data, columnNames);
            tblUsers.setModel(model);

            
            }
        }
        else {
            lblUsername.setText("Logged in as: " + MovieManager.getLoggedInUser().getUsername()+ "("+ MovieManager.getLoggedInUser().getRole()+")");
            spTableUsers.setVisible(false);
            
        }
       
        
    }
     else {
    JOptionPane.showMessageDialog(this, "No user is logged in.", "Error", JOptionPane.ERROR_MESSAGE);    
}   
        
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsername = new javax.swing.JLabel();
        spTableUsers = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        btnLogOut = new javax.swing.JButton();

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        spTableUsers.setViewportView(tblUsers);

        btnLogOut.setForeground(new java.awt.Color(255, 0, 0));
        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(spTableUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(367, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(spTableUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(266, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        MovieManager.setLoggedInUser(null);  
        Window parentWindow = SwingUtilities.getWindowAncestor(this);
        if (parentWindow instanceof MovieManager movieManager) {
        movieManager.handleLogout();   
    }

    MessageUtils.showInformationMessage("Logout", "You’ve been logged out.");
    }//GEN-LAST:event_btnLogOutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JScrollPane spTableUsers;
    private javax.swing.JTable tblUsers;
    // End of variables declaration//GEN-END:variables
}
